[I 03:04:24.461 NotebookApp] Serving notebooks from local directory: /home/ubuntu
[I 03:04:24.461 NotebookApp] Jupyter Notebook 6.4.4 is running at:
[I 03:04:24.461 NotebookApp] http://localhost:8888/
[I 03:04:24.461 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 03:04:36.250 NotebookApp] 302 POST /login?next=%2F (127.0.0.1) 107.140000ms
[I 03:04:36.299 NotebookApp] 302 GET / (127.0.0.1) 0.540000ms
/home/ubuntu/miniconda3/lib/python3.9/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 03:04:43.774 NotebookApp] Notebook HW4/Task 1.ipynb is not trusted
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x7fac1e2915e0>(<Future finis...igin\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7fac1e2915e0>(<Future finis...igin\r\n\r\n'>)>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-17' coro=<HTTP1ServerConnection._server_request_loop() running at /home/ubuntu/miniconda3/lib/python3.9/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /api/co...rigin\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/ubuntu/miniconda3/lib/python3.9/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-43' coro=<MappingKernelManager.start_kernel() running at /home/ubuntu/miniconda3/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py:176> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/ubuntu/miniconda3/lib/python3.9/site-packages/tornado/ioloop.py:688]> is being executed.
[I 03:04:43.985 NotebookApp] Kernel started: 7cbd8adb-5cab-4cc4-b95f-d44d6dfcecd3, name: python3
[W 03:04:44.030 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20211005030424 (127.0.0.1) 15.520000ms referer=http://localhost:8000/notebooks/HW4/Task%201.ipynb
/home/ubuntu/miniconda3/lib/python3.9/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 03:04:50.181 NotebookApp] Saving file at /HW4/Task 1.ipynb
[I 03:04:50.242 NotebookApp] Starting buffering for 7cbd8adb-5cab-4cc4-b95f-d44d6dfcecd3:92e25fbcfe52427088aed79cda892ff6
[I 03:04:53.053 NotebookApp] Kernel shutdown: 7cbd8adb-5cab-4cc4-b95f-d44d6dfcecd3
[I 03:05:02.658 NotebookApp] interrupted
Serving notebooks from local directory: /home/ubuntu
0 active kernels
Jupyter Notebook 6.4.4 is running at:
http://localhost:8888/
Shutdown this notebook server (y/[n])? [C 03:05:02.765 NotebookApp] received signal 2, stopping
[I 03:05:02.766 NotebookApp] Shutting down 0 kernels
[I 03:05:02.766 NotebookApp] Shutting down 0 terminals
